version: '3'

services:
  web:
    build: .
    container_name: paribhasha_web
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn PBackend.wsgi:application --bind 0.0.0.0:8000


    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env



