# Generated by Django 4.2.20 on 2025-03-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paribhasha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hindi', models.CharField(max_length=100, unique=True)),
                ('hinglish', models.CharField(max_length=100)),
                ('pageno', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paribhasha',
                'verbose_name_plural': 'Paribhasha',
            },
        ),
        migrations.CreateModel(
            name='ParibhashaLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=600)),
                ('paribhasha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paribhasha', to='dictionary.paribhasha')),
            ],
            options={
                'verbose_name': 'Paribhasha Line',
                'verbose_name_plural': 'Paribhasha Lines',
            },
        ),
    ]
