# Generated by Django 4.2.20 on 2025-03-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hindi', models.CharField(max_length=100, unique=True)),
                ('hinglish', models.CharField(max_length=100)),
                ('pageno', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
            },
        ),
        migrations.AlterModelOptions(
            name='paribhasha',
            options={'verbose_name': 'Paribhasha', 'verbose_name_plural': 'Paribhashas'},
        ),
        migrations.RemoveField(
            model_name='paribhasha',
            name='hindi',
        ),
        migrations.RemoveField(
            model_name='paribhasha',
            name='hinglish',
        ),
        migrations.RemoveField(
            model_name='paribhasha',
            name='pageno',
        ),
        migrations.AddField(
            model_name='paribhasha',
            name='description',
            field=models.TextField(default='test', max_length=600),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ParibhashaLine',
        ),
        migrations.AddField(
            model_name='paribhasha',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paribhashas', to='dictionary.word'),
        ),
    ]
