# Generated by Django 4.2.20 on 2025-03-11 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0002_word_alter_paribhasha_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='review_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
