# Generated by Django 4.2.20 on 2025-03-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_word_review_by_word_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paribhasha',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
